# Generated by Django 2.2.10 on 2021-04-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type_question',
            field=models.CharField(choices=[('text', 'ответ текстом'), ('single_value', 'ответ с выбором одного значения'), ('multi_value', 'ответ с выбором нескольких вариантов')], max_length=30),
        ),
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
