# Generated by Django 2.2.10 on 2021-04-20 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210421_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.Survey', verbose_name='Опрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type_question',
            field=models.CharField(choices=[('text', 'ответ текстом'), ('single_value', 'ответ с выбором одного значения'), ('multi_value', 'ответ с выбором нескольких вариантов')], max_length=30, verbose_name='Тип вопроса'),
        ),
    ]
