# Generated by Django 2.2.10 on 2021-04-21 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_answer_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerChoiseUnite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_answer', models.DateField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Answer', verbose_name='Вопрос')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Choice', verbose_name='Вариант ответа')),
            ],
        ),
    ]
