# Generated by Django 2.2.10 on 2021-04-21 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_answerchoiseunite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='multi_value',
            field=models.ManyToManyField(blank=True, to='api.Choice', verbose_name='Ответ с выбором нескольких вариантов'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.Question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='single_value',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='single_value_answers', to='api.Choice', verbose_name='Ответ с выбором одного значения'),
        ),
    ]
