# Generated by Django 2.2.10 on 2021-04-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210421_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(blank=True, verbose_name='Ответ текстом'),
        ),
    ]
