# Generated by Django 2.2.10 on 2021-04-22 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210421_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='date_finish',
            field=models.DateTimeField(db_index=True, verbose_name='Дата окончания'),
        ),
    ]
